language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq gcc

script:
- gcc cfm-seriation.c -lm -lpthread -lrt -o cfm-seriation
- ./cfm-seriation f=data/Escherichia_coli.dat

install: true
